config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
 resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @micropost = current_user.microposts.build if logged_in?
    @feed_items = current_user.feed.paginate(page: params[:page]) if logged_in?
  end

  def help
  end
  def about
  end
  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  Abdul Shahid is a Grade 12 student at Central Peel SS. In Brampton Ontario.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Abdul Shahid at: <strong>Abdulrsno1@gmail.com</strong>
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
    Get help at <a href = "http://www.google.ca">Google</a>
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
  <div id = home>
    <div class="center jumbotron">
      <h1 class= "title">Welcome to Clatter</h1>
    
      <h2 class = "synopsis">
        This is a practice application made by Abdul Shahid
      </h2>
    
      <%= link_to "Sign up", signup_path, class: "btn btn-lg btn-primary" %>
      <%= link_to "Log in", login_path, class: "btn btn-lg btn-info" %>
  
    </div>
  <%end%>
</div>